// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agaslhilgfibvmdiajxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnYXNsaGlsZ2ZpYnZtZGlhanhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTA4MjMsImV4cCI6MjA1NjU4NjgyM30.90B1XL3HtkBJ0_iZVjSglCYerH73dcuXWtn8ufnMfyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);